local M = {}

function M.setup(palette)
    local p = palette
    local highlights = {
        -- Editor UI
        Normal = { fg = p.text[900], bg = p.background[50] },
        SignColumn = { bg = p.background[50] },
        MsgArea = { fg = p.text[800], bg = p.background[50] },
        ModeMsg = { fg = p.text[800], bg = p.background[50], bold = true },
        MsgSeparator = { fg = p.text[800], bg = p.background[50] },
        SpellBad = { sp = p.primary[500], undercurl = true },
        SpellCap = { sp = p.secondary[500], undercurl = true },
        SpellLocal = { sp = p.accent[500], undercurl = true },
        SpellRare = { sp = p.primary[400], undercurl = true },
        NormalNC = { fg = p.text[800], bg = p.background[50] },
        Pmenu = { fg = p.text[800], bg = p.background[100] },
        PmenuSel = { fg = p.background[50], bg = p.primary[500], bold = true },
        PmenuSbar = { bg = p.background[200] },
        PmenuThumb = { bg = p.background[400] },
        WildMenu = { fg = p.background[50], bg = p.primary[500], bold = true },
        Folded = { fg = p.text[600], bg = p.background[100] },
        FoldColumn = { fg = p.text[600], bg = p.background[100] },
        LineNr = { fg = p.background[400] },
        CursorLineNr = { fg = p.primary[500], bold = true },
        CursorLine = { bg = p.background[100] },
        CursorColumn = { bg = p.background[100] },
        ColorColumn = { bg = p.background[100] },
        Whitespace = { fg = p.background[200] },
        VertSplit = { fg = p.background[200], bg = p.background[50] },
        WinSeparator = { fg = p.background[200], bg = p.background[50] },
        StatusLine = { fg = p.text[800], bg = p.background[100] },
        StatusLineNC = { fg = p.text[500], bg = p.background[50] },
        Cursor = { fg = p.background[50], bg = p.text[900] },
        TermCursor = { fg = p.background[50], bg = p.text[900] },
        TermCursorNC = { fg = p.background[50], bg = p.text[900] },
        Visual = { bg = p.background[300] },
        VisualNOS = { bg = p.background[300] },
        Search = { fg = p.background[50], bg = p.primary[500] },
        IncSearch = { fg = p.background[50], bg = p.secondary[500] },
        CurSearch = { fg = p.background[50], bg = p.secondary[500] },
        MatchParen = { fg = p.primary[500], bold = true },
        Directory = { fg = p.primary[500], bold = true },
        Title = { fg = p.primary[500], bold = true },
        Question = { fg = p.primary[500], bold = true },
        MoreMsg = { fg = p.primary[500], bold = true },
        ErrorMsg = { fg = p.background[50], bg = p.accent[500] },
        WarningMsg = { fg = p.primary[500], bold = true },
        NonText = { fg = p.background[300] },
        SpecialKey = { fg = p.background[300] },

        -- Syntax
        Comment = { fg = p.text[500], italic = true },
        Constant = { fg = p.accent[400] },
        String = { fg = p.accent[300] },
        Character = { fg = p.accent[400] },
        Number = { fg = p.primary[400] },
        Boolean = { fg = p.primary[400] },
        Float = { fg = p.primary[400] },
        Identifier = { fg = p.text[800] },
        Function = { fg = p.secondary[400] },
        Statement = { fg = p.primary[500] },
        Conditional = { fg = p.primary[500] },
        Repeat = { fg = p.primary[500] },
        Label = { fg = p.primary[500] },
        Operator = { fg = p.text[700] },
        Keyword = { fg = p.primary[500], italic = true },
        Exception = { fg = p.primary[500] },
        PreProc = { fg = p.secondary[500] },
        Include = { fg = p.secondary[500] },
        Define = { fg = p.secondary[500] },
        Macro = { fg = p.secondary[500] },
        PreCondit = { fg = p.secondary[500] },
        Type = { fg = p.secondary[300] },
        StorageClass = { fg = p.secondary[300] },
        Structure = { fg = p.secondary[300] },
        Typedef = { fg = p.secondary[300] },
        Special = { fg = p.accent[500] },
        SpecialChar = { fg = p.accent[500] },
        Tag = { fg = p.accent[500] },
        Delimiter = { fg = p.text[600] },
        SpecialComment = { fg = p.text[600] },
        Debug = { fg = p.primary[500] },
        Underlined = { underline = true },
        Ignore = { fg = p.text[500] },
        Error = { fg = p.background[50], bg = p.accent[500] },
        Todo = { fg = p.background[50], bg = p.primary[500] },

        -- Treesitter
        ["@variable"] = { fg = p.text[900] },
        ["@variable.builtin"] = { fg = p.primary[400] },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { fg = p.secondary[400] },
        ["@keyword"] = { link = "Keyword" },
        ["@string"] = { link = "String" },
        ["@type"] = { link = "Type" },
        ["@constructor"] = { fg = p.secondary[300] },
        ["@property"] = { fg = p.text[800] },
        ["@field"] = { fg = p.text[800] },
        ["@parameter"] = { fg = p.text[800] },
        ["@comment"] = { link = "Comment" },
        ["@punctuation.delimiter"] = { fg = p.text[600] },
        ["@punctuation.bracket"] = { fg = p.text[600] },
        ["@tag"] = { fg = p.primary[500] },
        ["@tag.attribute"] = { fg = p.secondary[400] },
        ["@tag.delimiter"] = { fg = p.text[600] },
    }

    for group, hl in pairs(highlights) do
        vim.api.nvim_set_hl(0, group, hl)
    end
end

return M